version: '3.1'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: wVe3ilFQqICufRBYYDSNUkd1V03
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: wVe3ilFQqICufRBYYDSNUkd1V03
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
